/**
 * DDL (Data Definition Language) tests
 * Tests for CREATE, ALTER, DROP statements
 */

import {
  parseOne,
  dialects,
  isCreateTable,
  isCreateView,
  isCreateIndex,
  isAlterTable,
  isDrop,
} from '../test-utils';

describe('CREATE TABLE', () => {
  test('parse basic CREATE TABLE', () => {
    const stmt = parseOne('CREATE TABLE t (id INT)');
    expect(isCreateTable(stmt)).toBe(true);
  });

  test('parse CREATE TABLE with multiple columns', () => {
    parseOne('CREATE TABLE t (id INT, name VARCHAR(255), created_at TIMESTAMP)');
  });

  test('parse CREATE TABLE IF NOT EXISTS', () => {
    parseOne('CREATE TABLE IF NOT EXISTS t (id INT)');
  });

  test('parse CREATE TEMPORARY TABLE', () => {
    parseOne('CREATE TEMPORARY TABLE t (id INT)');
    parseOne('CREATE TEMP TABLE t (id INT)');
  });

  test('parse CREATE OR REPLACE TABLE', () => {
    parseOne('CREATE OR REPLACE TABLE t (id INT)', dialects.snowflake);
  });

  describe('Column constraints', () => {
    test('parse NOT NULL', () => {
      parseOne('CREATE TABLE t (id INT NOT NULL)');
    });

    test('parse NULL', () => {
      parseOne('CREATE TABLE t (id INT NULL)');
    });

    test('parse PRIMARY KEY', () => {
      parseOne('CREATE TABLE t (id INT PRIMARY KEY)');
    });

    test('parse UNIQUE', () => {
      parseOne('CREATE TABLE t (email VARCHAR(255) UNIQUE)');
    });

    test('parse DEFAULT', () => {
      parseOne('CREATE TABLE t (status VARCHAR(10) DEFAULT \'active\')');
      parseOne('CREATE TABLE t (count INT DEFAULT 0)');
    });

    test('parse CHECK', () => {
      parseOne('CREATE TABLE t (age INT CHECK (age >= 0))');
    });

    test('parse REFERENCES', () => {
      parseOne('CREATE TABLE t (parent_id INT REFERENCES parent(id))');
    });

    test('parse AUTO_INCREMENT (MySQL)', () => {
      parseOne('CREATE TABLE t (id INT AUTO_INCREMENT)', dialects.mysql);
    });

    test('parse IDENTITY (MSSQL)', () => {
      parseOne('CREATE TABLE t (id INT IDENTITY)', dialects.mssql);
      parseOne('CREATE TABLE t (id INT IDENTITY(1, 1))', dialects.mssql);
    });

    test('parse GENERATED (PostgreSQL)', () => {
      parseOne('CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY)', dialects.postgresql);
      parseOne('CREATE TABLE t (id INT GENERATED BY DEFAULT AS IDENTITY)', dialects.postgresql);
    });

    test('parse COLLATE', () => {
      parseOne('CREATE TABLE t (name VARCHAR(255) COLLATE utf8mb4_unicode_ci)', dialects.mysql);
    });

    test('parse COMMENT (MySQL)', () => {
      parseOne("CREATE TABLE t (id INT COMMENT 'primary key')", dialects.mysql);
    });
  });

  describe('Table constraints', () => {
    test('parse PRIMARY KEY constraint', () => {
      parseOne('CREATE TABLE t (id INT, PRIMARY KEY (id))');
      parseOne('CREATE TABLE t (id INT, name VARCHAR(255), PRIMARY KEY (id, name))');
    });

    test('parse UNIQUE constraint', () => {
      parseOne('CREATE TABLE t (id INT, UNIQUE (id))');
      parseOne('CREATE TABLE t (email VARCHAR(255), UNIQUE (email))');
    });

    test('parse FOREIGN KEY constraint', () => {
      parseOne('CREATE TABLE t (parent_id INT, FOREIGN KEY (parent_id) REFERENCES parent(id))');
      parseOne('CREATE TABLE t (id INT, FOREIGN KEY (id) REFERENCES parent(id) ON DELETE CASCADE)');
    });

    test('parse CHECK constraint', () => {
      parseOne('CREATE TABLE t (age INT, CHECK (age >= 18))');
    });

    test('parse named constraints', () => {
      parseOne('CREATE TABLE t (id INT, CONSTRAINT pk_t PRIMARY KEY (id))');
      parseOne('CREATE TABLE t (id INT, CONSTRAINT uq_id UNIQUE (id))');
    });
  });

  describe('Data types', () => {
    test('parse integer types', () => {
      parseOne('CREATE TABLE t (a TINYINT, b SMALLINT, c INT, d BIGINT)');
    });

    test('parse floating point types', () => {
      parseOne('CREATE TABLE t (a FLOAT, b DOUBLE, c DECIMAL(10, 2))');
    });

    test('parse string types', () => {
      parseOne('CREATE TABLE t (a CHAR(10), b VARCHAR(255), c TEXT)');
    });

    test('parse date/time types', () => {
      parseOne('CREATE TABLE t (a DATE, b TIME, c DATETIME, d TIMESTAMP)');
    });

    test('parse binary types', () => {
      parseOne('CREATE TABLE t (a BINARY(16), b VARBINARY(255), c BLOB)');
    });

    test('parse boolean type', () => {
      parseOne('CREATE TABLE t (active BOOLEAN)');
    });

    test('parse UUID type', () => {
      parseOne('CREATE TABLE t (id UUID)', dialects.postgresql);
    });

    test('parse JSON types', () => {
      parseOne('CREATE TABLE t (data JSON)', dialects.mysql);
      parseOne('CREATE TABLE t (data JSONB)', dialects.postgresql);
    });

    test('parse array types (PostgreSQL)', () => {
      parseOne('CREATE TABLE t (tags TEXT[])', dialects.postgresql);
      parseOne('CREATE TABLE t (matrix INT[][])', dialects.postgresql);
    });
  });

  describe('CREATE TABLE AS SELECT', () => {
    test('parse CREATE TABLE AS', () => {
      parseOne('CREATE TABLE t AS SELECT * FROM other');
    });

    test.skip('parse CREATE TABLE AS with columns', () => {
      // Column list in CREATE TABLE AS not yet fully supported
      parseOne('CREATE TABLE t (id, name) AS SELECT a, b FROM other');
    });
  });

  describe('Table options', () => {
    test('parse ENGINE (MySQL)', () => {
      parseOne('CREATE TABLE t (id INT) ENGINE = InnoDB', dialects.mysql);
    });

    test('parse CHARSET (MySQL)', () => {
      parseOne('CREATE TABLE t (id INT) DEFAULT CHARSET = utf8mb4', dialects.mysql);
    });

    test('parse COLLATE (MySQL)', () => {
      parseOne('CREATE TABLE t (id INT) COLLATE = utf8mb4_unicode_ci', dialects.mysql);
    });

    test('parse COMMENT (MySQL)', () => {
      parseOne("CREATE TABLE t (id INT) COMMENT = 'test table'", dialects.mysql);
    });
  });
});

describe('CREATE VIEW', () => {
  test('parse CREATE VIEW', () => {
    const stmt = parseOne('CREATE VIEW v AS SELECT * FROM t');
    expect(isCreateView(stmt)).toBe(true);
  });

  test('parse CREATE VIEW with columns', () => {
    parseOne('CREATE VIEW v (a, b) AS SELECT x, y FROM t');
  });

  test('parse CREATE OR REPLACE VIEW', () => {
    parseOne('CREATE OR REPLACE VIEW v AS SELECT * FROM t');
  });

  test('parse CREATE MATERIALIZED VIEW', () => {
    parseOne('CREATE MATERIALIZED VIEW v AS SELECT * FROM t', dialects.postgresql);
  });

  test('parse CREATE VIEW IF NOT EXISTS', () => {
    parseOne('CREATE VIEW IF NOT EXISTS v AS SELECT * FROM t');
  });
});

describe('CREATE INDEX', () => {
  test('parse CREATE INDEX', () => {
    const stmt = parseOne('CREATE INDEX idx ON t (col)');
    expect(isCreateIndex(stmt)).toBe(true);
  });

  test('parse CREATE INDEX with multiple columns', () => {
    parseOne('CREATE INDEX idx ON t (col1, col2)');
  });

  test('parse CREATE UNIQUE INDEX', () => {
    parseOne('CREATE UNIQUE INDEX idx ON t (col)');
  });

  test('parse CREATE INDEX IF NOT EXISTS', () => {
    parseOne('CREATE INDEX IF NOT EXISTS idx ON t (col)');
  });

  test('parse CREATE INDEX with USING (PostgreSQL)', () => {
    parseOne('CREATE INDEX idx ON t USING btree (col)', dialects.postgresql);
    parseOne('CREATE INDEX idx ON t USING hash (col)', dialects.postgresql);
  });

  test('parse CREATE INDEX CONCURRENTLY (PostgreSQL)', () => {
    parseOne('CREATE INDEX CONCURRENTLY idx ON t (col)', dialects.postgresql);
  });

  test('parse CREATE INDEX with WHERE (PostgreSQL)', () => {
    parseOne('CREATE INDEX idx ON t (col) WHERE active = true', dialects.postgresql);
  });
});

describe('ALTER TABLE', () => {
  test('parse ALTER TABLE ADD COLUMN', () => {
    const stmt = parseOne('ALTER TABLE t ADD COLUMN new_col INT');
    expect(isAlterTable(stmt)).toBe(true);
  });

  test('parse ALTER TABLE ADD without COLUMN keyword', () => {
    parseOne('ALTER TABLE t ADD new_col INT');
  });

  test('parse ALTER TABLE DROP COLUMN', () => {
    parseOne('ALTER TABLE t DROP COLUMN old_col');
    parseOne('ALTER TABLE t DROP old_col');
  });

  test('parse ALTER TABLE RENAME COLUMN', () => {
    parseOne('ALTER TABLE t RENAME COLUMN old_name TO new_name');
  });

  test('parse ALTER TABLE RENAME TABLE', () => {
    parseOne('ALTER TABLE t RENAME TO new_name');
  });

  test('parse ALTER TABLE ALTER COLUMN', () => {
    parseOne('ALTER TABLE t ALTER COLUMN col SET DEFAULT 0');
    parseOne('ALTER TABLE t ALTER COLUMN col DROP DEFAULT');
    parseOne('ALTER TABLE t ALTER COLUMN col SET NOT NULL');
    parseOne('ALTER TABLE t ALTER COLUMN col DROP NOT NULL');
  });

  test('parse ALTER TABLE MODIFY COLUMN (MySQL)', () => {
    parseOne('ALTER TABLE t MODIFY COLUMN col VARCHAR(100)', dialects.mysql);
  });

  test('parse ALTER TABLE CHANGE COLUMN (MySQL)', () => {
    parseOne('ALTER TABLE t CHANGE COLUMN old_col new_col INT', dialects.mysql);
  });

  test('parse ALTER TABLE ADD CONSTRAINT', () => {
    parseOne('ALTER TABLE t ADD CONSTRAINT pk PRIMARY KEY (id)');
    parseOne('ALTER TABLE t ADD CONSTRAINT fk FOREIGN KEY (parent_id) REFERENCES parent(id)');
  });

  test('parse ALTER TABLE DROP CONSTRAINT', () => {
    parseOne('ALTER TABLE t DROP CONSTRAINT constraint_name');
  });

  test('parse ALTER TABLE with IF EXISTS', () => {
    parseOne('ALTER TABLE IF EXISTS t ADD COLUMN col INT', dialects.postgresql);
  });
});

describe('DROP statements', () => {
  test('parse DROP TABLE', () => {
    const stmt = parseOne('DROP TABLE t');
    expect(isDrop(stmt)).toBe(true);
  });

  test('parse DROP TABLE IF EXISTS', () => {
    parseOne('DROP TABLE IF EXISTS t');
  });

  test('parse DROP TABLE multiple tables', () => {
    parseOne('DROP TABLE t1, t2, t3');
  });

  test('parse DROP TABLE CASCADE', () => {
    parseOne('DROP TABLE t CASCADE', dialects.postgresql);
  });

  test('parse DROP TABLE RESTRICT', () => {
    parseOne('DROP TABLE t RESTRICT', dialects.postgresql);
  });

  test('parse DROP VIEW', () => {
    parseOne('DROP VIEW v');
    parseOne('DROP VIEW IF EXISTS v');
  });

  test('parse DROP INDEX', () => {
    parseOne('DROP INDEX idx');
    parseOne('DROP INDEX IF EXISTS idx');
  });

  test('parse DROP SCHEMA', () => {
    parseOne('DROP SCHEMA s', dialects.postgresql);
    parseOne('DROP SCHEMA IF EXISTS s CASCADE', dialects.postgresql);
  });

  test('parse DROP DATABASE', () => {
    parseOne('DROP DATABASE db');
    parseOne('DROP DATABASE IF EXISTS db');
  });
});

describe('CREATE SCHEMA', () => {
  test('parse CREATE SCHEMA', () => {
    parseOne('CREATE SCHEMA my_schema', dialects.postgresql);
  });

  test('parse CREATE SCHEMA IF NOT EXISTS', () => {
    parseOne('CREATE SCHEMA IF NOT EXISTS my_schema', dialects.postgresql);
  });

  test('parse CREATE SCHEMA AUTHORIZATION', () => {
    parseOne('CREATE SCHEMA my_schema AUTHORIZATION user_name', dialects.postgresql);
  });
});

describe('CREATE DATABASE', () => {
  test('parse CREATE DATABASE', () => {
    parseOne('CREATE DATABASE mydb');
  });

  test('parse CREATE DATABASE IF NOT EXISTS', () => {
    parseOne('CREATE DATABASE IF NOT EXISTS mydb');
  });
});

describe('RENAME', () => {
  test('parse RENAME TABLE (MySQL)', () => {
    parseOne('RENAME TABLE old_name TO new_name', dialects.mysql);
  });
});

describe('Complex DDL scenarios', () => {
  test('parse table with all constraint types', () => {
    parseOne(`
      CREATE TABLE users (
        id INT PRIMARY KEY,
        email VARCHAR(255) UNIQUE NOT NULL,
        age INT CHECK (age >= 18),
        parent_id INT REFERENCES parent(id),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);
  });

  test('parse table with composite primary key', () => {
    parseOne('CREATE TABLE t (a INT, b INT, PRIMARY KEY (a, b))');
  });

  test('parse table with multiple foreign keys', () => {
    parseOne(`
      CREATE TABLE t (
        id INT PRIMARY KEY,
        user_id INT REFERENCES users(id),
        product_id INT REFERENCES products(id)
      )
    `);
  });
});
